package com.example.proxy;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public final class Iso3166 {
    public static final Map<String, String> CODE_TO_COUNTRY;

    static {
        Map<String, String> map = new HashMap<>();
        map.put("AD", "Andorra");
        map.put("AE", "United Arab Emirates");
        map.put("AF", "Afghanistan");
        map.put("AG", "Antigua & Barbuda");
        map.put("AI", "Anguilla");
        map.put("AL", "Albania");
        map.put("AM", "Armenia");
        map.put("AN", "Netherlands Antilles");
        map.put("AO", "Angola");
        map.put("AQ", "Antarctica");
        map.put("AR", "Argentina");
        map.put("AS", "American Samoa");
        map.put("AT", "Austria");
        map.put("AU", "Australia");
        map.put("AW", "Aruba");
        map.put("AZ", "Azerbaijan");
        map.put("BA", "Bosnia and Herzegovina");
        map.put("BB", "Barbados");
        map.put("BD", "Bangladesh");
        map.put("BE", "Belgium");
        map.put("BF", "Burkina Faso");
        map.put("BG", "Bulgaria");
        map.put("BH", "Bahrain");
        map.put("BI", "Burundi");
        map.put("BJ", "Benin");
        map.put("BM", "Bermuda");
        map.put("BN", "Brunei Darussalam");
        map.put("BO", "Bolivia");
        map.put("BR", "Brazil");
        map.put("BS", "Bahama");
        map.put("BT", "Bhutan");
        map.put("BU", "Burma (no longer exists)");
        map.put("BV", "Bouvet Island");
        map.put("BW", "Botswana");
        map.put("BY", "Belarus");
        map.put("BZ", "Belize");
        map.put("CA", "Canada");
        map.put("CC", "Cocos (Keeling) Islands");
        map.put("CF", "Central African Republic");
        map.put("CG", "Congo");
        map.put("CH", "Switzerland");
        map.put("CI", "Cote D\"ivoire (Ivory Coast)");
        map.put("CK", "Cook Iislands");
        map.put("CL", "Chile");
        map.put("CM", "Cameroon");
        map.put("CN", "China");
        map.put("CO", "Colombia");
        map.put("CR", "Costa Rica");
        map.put("CS", "Czechoslovakia (no longer exists)");
        map.put("CU", "Cuba");
        map.put("CV", "Cape Verde");
        map.put("CX", "Christmas Island");
        map.put("CY", "Cyprus");
        map.put("CZ", "Czech Republic");
        map.put("DD", "German Democratic Republic (no longer exists)");
        map.put("DE", "Germany");
        map.put("DJ", "Djibouti");
        map.put("DK", "Denmark");
        map.put("DM", "Dominica");
        map.put("DO", "Dominican Republic");
        map.put("DZ", "Algeria");
        map.put("EC", "Ecuador");
        map.put("EE", "Estonia");
        map.put("EG", "Egypt");
        map.put("EH", "Western Sahara");
        map.put("ER", "Eritrea");
        map.put("ES", "Spain");
        map.put("ET", "Ethiopia");
        map.put("FI", "Finland");
        map.put("FJ", "Fiji");
        map.put("FK", "Falkland Islands (Malvinas)");
        map.put("FM", "Micronesia");
        map.put("FO", "Faroe Islands");
        map.put("FR", "France");
        map.put("FX", "France, Metropolitan");
        map.put("GA", "Gabon");
        map.put("GB", "United Kingdom (Great Britain)");
        map.put("GD", "Grenada");
        map.put("GE", "Georgia");
        map.put("GF", "French Guiana");
        map.put("GH", "Ghana");
        map.put("GI", "Gibraltar");
        map.put("GL", "Greenland");
        map.put("GM", "Gambia");
        map.put("GN", "Guinea");
        map.put("GP", "Guadeloupe");
        map.put("GQ", "Equatorial Guinea");
        map.put("GR", "Greece");
        map.put("GS", "South Georgia and the South Sandwich Islands");
        map.put("GT", "Guatemala");
        map.put("GU", "Guam");
        map.put("GW", "Guinea-Bissau");
        map.put("GY", "Guyana");
        map.put("HK", "Hong Kong");
        map.put("HM", "Heard & McDonald Islands");
        map.put("HN", "Honduras");
        map.put("HR", "Croatia");
        map.put("HT", "Haiti");
        map.put("HU", "Hungary");
        map.put("ID", "Indonesia");
        map.put("IE", "Ireland");
        map.put("IL", "Israel");
        map.put("IN", "India");
        map.put("IO", "British Indian Ocean Territory");
        map.put("IQ", "Iraq");
        map.put("IR", "Islamic Republic of Iran");
        map.put("IS", "Iceland");
        map.put("IT", "Italy");
        map.put("JM", "Jamaica");
        map.put("JO", "Jordan");
        map.put("JP", "Japan");
        map.put("KE", "Kenya");
        map.put("KG", "Kyrgyzstan");
        map.put("KH", "Cambodia");
        map.put("KI", "Kiribati");
        map.put("KM", "Comoros");
        map.put("KN", "St. Kitts and Nevis");
        map.put("KP", "Korea, Democratic People\"s Republic of");
        map.put("KR", "Korea, Republic of");
        map.put("KW", "Kuwait");
        map.put("KY", "Cayman Islands");
        map.put("KZ", "Kazakhstan");
        map.put("LA", "Lao People\"s Democratic Republic");
        map.put("LB", "Lebanon");
        map.put("LC", "Saint Lucia");
        map.put("LI", "Liechtenstein");
        map.put("LK", "Sri Lanka");
        map.put("LR", "Liberia");
        map.put("LS", "Lesotho");
        map.put("LT", "Lithuania");
        map.put("LU", "Luxembourg");
        map.put("LV", "Latvia");
        map.put("LY", "Libyan Arab Jamahiriya");
        map.put("MA", "Morocco");
        map.put("MC", "Monaco");
        map.put("MD", "Moldova, Republic of");
        map.put("MG", "Madagascar");
        map.put("MH", "Marshall Islands");
        map.put("ML", "Mali");
        map.put("MN", "Mongolia");
        map.put("MM", "Myanmar");
        map.put("MO", "Macau");
        map.put("MP", "Northern Mariana Islands");
        map.put("MQ", "Martinique");
        map.put("MR", "Mauritania");
        map.put("MS", "Monserrat");
        map.put("MT", "Malta");
        map.put("MU", "Mauritius");
        map.put("MV", "Maldives");
        map.put("MW", "Malawi");
        map.put("MX", "Mexico");
        map.put("MY", "Malaysia");
        map.put("MZ", "Mozambique");
        map.put("NA", "Namibia");
        map.put("NC", "New Caledonia");
        map.put("NE", "Niger");
        map.put("NF", "Norfolk Island");
        map.put("NG", "Nigeria");
        map.put("NI", "Nicaragua");
        map.put("NL", "Netherlands");
        map.put("NO", "Norway");
        map.put("NP", "Nepal");
        map.put("NR", "Nauru");
        map.put("NT", "Neutral Zone (no longer exists)");
        map.put("NU", "Niue");
        map.put("NZ", "New Zealand");
        map.put("OM", "Oman");
        map.put("PA", "Panama");
        map.put("PE", "Peru");
        map.put("PF", "French Polynesia");
        map.put("PG", "Papua New Guinea");
        map.put("PH", "Philippines");
        map.put("PK", "Pakistan");
        map.put("PL", "Poland");
        map.put("PM", "St. Pierre & Miquelon");
        map.put("PN", "Pitcairn");
        map.put("PR", "Puerto Rico");
        map.put("PT", "Portugal");
        map.put("PW", "Palau");
        map.put("PY", "Paraguay");
        map.put("QA", "Qatar");
        map.put("RE", "Reunion");
        map.put("RO", "Romania");
        map.put("RU", "Russian Federation");
        map.put("RW", "Rwanda");
        map.put("SA", "Saudi Arabia");
        map.put("SB", "Solomon Islands");
        map.put("SC", "Seychelles");
        map.put("SD", "Sudan");
        map.put("SE", "Sweden");
        map.put("SG", "Singapore");
        map.put("SH", "St. Helena");
        map.put("SI", "Slovenia");
        map.put("SJ", "Svalbard & Jan Mayen Islands");
        map.put("SK", "Slovakia");
        map.put("SL", "Sierra Leone");
        map.put("SM", "San Marino");
        map.put("SN", "Senegal");
        map.put("SO", "Somalia");
        map.put("SR", "Suriname");
        map.put("ST", "Sao Tome & Principe");
        map.put("SU", "Union of Soviet Socialist Republics (no longer exists)");
        map.put("SV", "El Salvador");
        map.put("SY", "Syrian Arab Republic");
        map.put("SZ", "Swaziland");
        map.put("TC", "Turks & Caicos Islands");
        map.put("TD", "Chad");
        map.put("TF", "French Southern Territories");
        map.put("TG", "Togo");
        map.put("TH", "Thailand");
        map.put("TJ", "Tajikistan");
        map.put("TK", "Tokelau");
        map.put("TM", "Turkmenistan");
        map.put("TN", "Tunisia");
        map.put("TO", "Tonga");
        map.put("TP", "East Timor");
        map.put("TR", "Turkey");
        map.put("TT", "Trinidad & Tobago");
        map.put("TV", "Tuvalu");
        map.put("TW", "Taiwan, Province of China");
        map.put("TZ", "Tanzania, United Republic of");
        map.put("UA", "Ukraine");
        map.put("UG", "Uganda");
        map.put("UK", "United Kingdom");
        map.put("UM", "United States Minor Outlying Islands");
        map.put("US", "United States of America");
        map.put("UY", "Uruguay");
        map.put("UZ", "Uzbekistan");
        map.put("VA", "Vatican City State (Holy See)");
        map.put("VC", "St. Vincent & the Grenadines");
        map.put("VE", "Venezuela");
        map.put("VG", "British Virgin Islands");
        map.put("VI", "United States Virgin Islands");
        map.put("VN", "Viet Nam");
        map.put("VU", "Vanuatu");
        map.put("WF", "Wallis & Futuna Islands");
        map.put("WS", "Samoa");
        map.put("YD", "Democratic Yemen (no longer exists)");
        map.put("YE", "Yemen");
        map.put("YT", "Mayotte");
        map.put("YU", "Yugoslavia");
        map.put("ZA", "South Africa");
        map.put("ZM", "Zambia");
        map.put("ZR", "Zaire");
        map.put("ZW", "Zimbabwe");
        map.put("ZZ", "Unknown or unspecified country");
        CODE_TO_COUNTRY = Collections.unmodifiableMap(map);
    }

    private Iso3166() {}
}